import gradio as gr
import openai
import os

# Load your OpenAI API key
openai.api_key = os.environ["OPENAI_API_KEY"]

# Set the cost per token for your pricing plan (example: $0.001/token)
COST_PER_TOKEN = 0.00002

def generate_joke(prompt):
    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=f"You are a joke bot. Create a funny joke about: {prompt}",
        max_tokens=100,
        n=1,
        stop=None,
        temperature=0.7,
    )
    joke = response.choices[0].text.strip()
    used_tokens = response['usage']['total_tokens']
    cost = used_tokens * COST_PER_TOKEN
    cost_info = f"\n\nTokens used: {used_tokens}, Cost: ${cost:.4f}"
    return joke + cost_info

iface = gr.Interface(
    fn=generate_joke,
    inputs=gr.inputs.Textbox(lines=1, label="Enter a topic for the joke (optional):"),
    outputs=gr.outputs.Textbox(label="Here's a joke for you!"),
    title="Joke Chatbot",
    description="Enter a topic and get a joke generated by OpenAI GPT-3.5!",
)

iface.launch()
